name: Emacs build and test
on:
  push:
    branches:
      - main
    paths:
      - "**.el"
      - "**.nix"
      - "flake.*"
  workflow_dispatch:
jobs:
  nix-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix flake check
      - run: nix build
